### ISSUE TITLE
Is it possible to get the HTML content of the body?

### ISSUE THREAD

**Issue by timstr97** [pushpak1300/cypress-mailpit#1]
Hey, first of all, thanks for this cool project!

My question would be if it is possible to get the HTML content of the body?
When i do this here, i only get the text of the email:

`cy.mhGetAllMails().mhFirst() .mhGetBody() .then((body) => {console.log(body)})`

Thanks in advance

**Comment by pushpak1300** [comment]
Yes, it is possible. I'll be releasing a new version very soon the current version is still in beta so API is still in very early stages.
For now, you can get the ID and do the subsequent call to this [API]( https://mailpit.axllent.org/docs/api-v1/view.html#get-/view/-ID-.html).

**Comment by timstr97** [comment]
Thanks, that was really helpful!

**Comment by pushpak1300** [comment]
Hey, this has been released v0.0.3
