### ISSUE TITLE
Add HTML body, Text body, Delete single mail, get ID and Message ID

### ISSUE THREAD

**Issue by jacobsenj** [pushpak1300/cypress-mailpit#2]
Hello,

I'm not so firm with using javascript, but i've extendend some stuff to get HTML, TEXT, ID, MessageID from an email and also a possibility to delete a single email.

I'll attach a patch file for my addtions.

Cheers
Jens

P.S. maybe all mh prefixes should get replaced with mp or something :)

[cypress-mailpit@0.0.2.patch](https://github.com/pushpak1300/cypress-mailpit/files/13526331/cypress-mailpit%400.0.2.patch)

Edit: I've changed the patch file to a pnpm patch command created one

**Comment by pushpak1300** [comment]
@jacobsenj new set of feature has been release in V1.0.0
