### ISSUE TITLE
Missing functions in 1.0

### ISSUE THREAD

**Issue by bartjuh4** [pushpak1300/cypress-mailpit#28]
Hi,

We are missing some functions in the new version of this package:

```
    cy.mhHasMailWithSubject('Some email subject');
    cy.mhHasMailTo('mail@sender.com');
```

Looks like we need a lot of extra code to re-create the exact same functionality. Are there any plans to add these functions?
Else we might be stuck on version 0.0.4

**Comment by pushpak1300** [comment]
@bartjuh4  
I wanted to let you know that our 1.0.0 version included some breaking changes, which altered certain functionalities. However, we plan to reintroduce support for the two functions you mentioned in the next minor versions. I will update you once that is done.

**Comment by pushpak1300** [comment]
Resolved in https://github.com/pushpak1300/cypress-mailpit/pull/29
