### ISSUE TITLE
Make the env variables bit more consistant

### ISSUE THREAD

**Issue by chrissmartin** [pushpak1300/cypress-mailpit#3]
Description
---
- The environment variables in the project do not have consistant casing. Do make it more consistant.
- Since Mailpit is a single word, we can keep it as `mailpitX`.
### Suggested Changes:
- `mailpitUrl`  
- `mailpitAuth`
- `mailPitUsername` -> `mailpitUsername`
- `mailPitPassword` -> `mailpitPassword`

Or the otherway around like `mailPitX`

**Comment by pushpak1300** [comment]
@chrissmartin new set of feature has been release in V1.0.0
