### ISSUE TITLE
Incorrectly spelled method `mailpitGetMailSpamAssainSummary`, should be `mailpitGetMailSpamAssassinSummary`

### ISSUE THREAD

**Issue by brandonb927** [pushpak1300/cypress-mailpit#30]
I noticed in the README that the method in this issue title is misspelled; an easy mistake. The actual method nor the type definition are not spelled `assassin` either:
- https://github.com/pushpak1300/cypress-mailpit/blob/013bd78c070f4d293e40b093a3ad119505690865/src/MailpitCommands.ts#L179
- https://github.com/pushpak1300/cypress-mailpit/blob/013bd78c070f4d293e40b093a3ad119505690865/cypress.d.ts#L97

**Comment by pushpak1300** [comment]
Thanks for reporting this issue.  @brandonb927  
Do you wan to create PR for this ?
