### ISSUE TITLE
Mail unexpectedly marked as read

### ISSUE THREAD

**Issue by GrayedFox** [pushpak1300/cypress-mailpit#33]
Hi there, thanks for this great little wrapper.

I was keen on just using your wrapper instead of interfacing with the Mailpit API but because `mailpitGetMail()` uses the [message summary endpoint](https://mailpit.axllent.org/docs/api-v1/view.html#get-/api/v1/message/-ID-) I can't easily fetch an email and not have it marked as read.

I can work around it by using `mailpitSearchEmails()` [here](https://github.com/pushpak1300/cypress-mailpit/blob/main/src/MailpitCommands.ts#L111) but there doesn't seem to be a way to get an attachment without also reading the email which means I conditionally need to send another custom request like so:

```
/**
 * Set read state of emails using mailpit API which helps us test and query emails more efficiently
 */
#setReadState(emailIds = ['latest'], readState = true) {
    return cy
        .request({
            method: 'PUT',
            url: `${cypressEnv.MAILPIT_URL}/api/v1/messages`,
            body: {
                IDs: emailIds,
                Read: readState
            }
        })
        .then(response => {
            if (response.status !== 200) {
                throw new Error(`Failed to read email. Status: ${response.status}, Body: ${response.body}`);
            }
            cy.log(`MAILPIT email with IDs: [${emailIds}] set to ${readState ? 'read' : 'unread'} (empty means all)`);
        });
}
```

This might actually be a limitation of the Mailpit API but if you're open to extending your methods with an `options: { keepUnread: true }` or something similar that would be nice. I don't mind an extra Mailpit request needing to fire, it's more that it's quite unexpected to fetch emails with the search command and see they remain unread only to get an email with the another method and see it's now being set as read.

Even just the addition of a wrapper which allows the plugins users to set the read state themselves would be cool, let me know if you'd like that in a PR and I'll get round to it :)

**Comment by pushpak1300** [comment]
Thanks @GrayedFox for this feature request. 
This feature has been released in https://github.com/pushpak1300/cypress-mailpit/releases/tag/v1.2.0
