### ISSUE TITLE
getting message body for specific email

### ISSUE THREAD

**Issue by gc-bianchi** [pushpak1300/cypress-mailpit#37]
Hello, I was looking at your documentation here 

https://www.npmjs.com/package/cypress-mailpit

I was wondering if there was a way of chaining your commands to get the text from a specific email? 

This does not seem to be working 

    cy.mailpitGetEmailsBySubject(
      "You've got a Quote from PC STUDIO for David Bowie"
    ).mailpitGetMailTextBody();

I need to be able to click a link within an email, or at the very least, grab the url from a button in the email, and then navigate to it. Is this possible?

**Comment by pushpak1300** [comment]
Okay let me try this. 
Also do you have multiple emails with this subject "You've got a Quote from PC STUDIO for David Bowie" ?

**Comment by pushpak1300** [comment]
```ts
cy.mailpitGetEmailsBySubject("You've got a Quote from PC STUDIO for David Bowie")
  .then((emails) => {
    // Assuming the first email is the one we want
    const email = emails[0];
    
    // Get the text body of the email
    const textBody = email.Text;
    
    // If you need to click a link or get a URL from the email
    const htmlBody = email.HTML;
    
    // Use a regular expression to find URLs in the HTML body
    const urlRegex = /(https?:\/\/[^\s]+)/g;
    const urls = htmlBody.match(urlRegex);
    
    if (urls && urls.length > 0) {
      // Assuming the first URL is the one you want to navigate to
      const targetUrl = urls[0];
      
      // Navigate to the URL
      cy.visit(targetUrl);
    } else {
      throw new Error('No URLs found in the email');
    }
  });
  ```
