### ISSUE TITLE
Feature Request: automatic waiting and retries for queries

### ISSUE THREAD

**Issue by a-kriya** [pushpak1300/cypress-mailpit#39]
Automatic waiting, retry-ability, flake resistance are some of the terms Cypress uses to describe one of the fundamental natures of its querying commands.

https://learn.cypress.io/cypress-fundamentals/waiting-and-retry-ability
https://docs.cypress.io/guides/core-concepts/retry-ability

As a large part of `cypress-mailpit` invovles querying, it would be awesome to have it behave similar to other native Cypress commands with a polling behavior until a timeout. Both the poll interval and timeout could be made configurable for flexibility.

Thank you for creating and maintaining this package.

**Comment by TobiasHH** [comment]
I also run into this Issue. I want to use the package for e2e Testing. With the actual behavior there ist only one request send. If the mail is not in the system at this time, the test fails. My workaround is to wait for some seconds after I performed the trigger action. It would be nice if the command is polling the mails until the conditions are satisfied or the timeout is reached  as stated in the comment before. Also the https://www.npmjs.com/package/cypress-mailhog plugin is working with this mechanism.

**Comment by pushpak1300** [comment]
Thanks @TobiasHH @a-kriya for using the package. I am just trying to find a way to give unified approach to give timeout and polling the request for that time. If you have any ideas please feel free to add that.

**Comment by TobiasHH** [comment]
I don't know if the following code helps. It is from the mailhog cypress Plugin which supports retryability.https://github.com/SMenigat/cypress-mailhog/blob/master/index.jsVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Pushpak Chhajed ***@***.***> Datum: 10.10.24  15:59  (GMT+01:00) An: pushpak1300/cypress-mailpit ***@***.***> Cc: TobiasHH ***@***.***>, Mention ***@***.***> Betreff: Re: [pushpak1300/cypress-mailpit] Feature Request: automatic waiting and retries for queries (Issue #39) 
Thanks @TobiasHH @a-kriya for using the package. I am just trying to find a way to give unified approach to give timeout and polling the request for that time. If you have any ideas please feel free to add that.

**Comment by pushpak1300** [comment]
@TobiasHH @a-kriya Please check linked MR to see if this is the behaviour is ideal.

**Comment by pushpak1300** [comment]
Release in https://github.com/pushpak1300/cypress-mailpit/releases/tag/v1.3.0 @TobiasHH @a-kriya

**Comment by a-jaouen** [comment]
Thank you @pushpak1300!
