### ISSUE TITLE
Error handling is mostly redundant as it is only executed on success status codes.

### ISSUE THREAD

**Issue by TobiasHH** [pushpak1300/cypress-mailpit#48]
As I understand and use Cypress in my work for 3 years the error handling is redundant.

https://docs.cypress.io/api/commands/request

The request has a build in error handler which is set to true. If the server answers with a non success status code like 4xx or 5xx the test failes automatically with a proper log.

The following code is only executed when the request answers with a success status code.
```
		.then((response) => {
				if (response.status !== 200) {
					throw new Error(`Failed to get messages. Status: ${response.status}, Body: ${response.body}`);
				}
				return response.body as MessagesSummary;
			});
```

property | default value| description
failOnStatusCode | true | Whether to fail on response codes other than 2xx and 3xx

To make the error handling work correctly set the property to false. Otherwise it can be removed from all commands.

**Comment by TobiasHH** [comment]
Is it possible to contribute in this project? It will be my first one 🙈

**Comment by pushpak1300** [comment]
Yes @TobiasHH. It will be great.

**Comment by TobiasHH** [comment]
Can't pust a new feat branch. Need some help.

`remote: Permission to pushpak1300/cypress-mailpit.git denied to TobiasHH.
fatal: unable to access 'https://github.com/pushpak1300/cypress-mailpit.git/': The requested URL returned error: 403`

**Comment by pushpak1300** [comment]
@TobiasHH, please start by forking the repository to your account. After forking, make your changes in the forked repository, and then push those changes.

You can follow this guide for more detailed instructions: [GitHub Forking Guide](https://gist.github.com/Chaser324/ce0505fbed06b947d962).

**Comment by pushpak1300** [comment]
@TobiasHH Are you able to solve the issue or you need more help here ?

**Comment by TobiasHH** [comment]
I just had time today to fork the project. I will try to implement the stuff the next days.

**Comment by TobiasHH** [comment]
I have another question. The custom commands seem to lack a custom logging. Is it OK if I add it in my implemention?

**Comment by TobiasHH** [comment]
Actual using the mailpit commands will display request in the command log. You can add custom names. So if you then use a mailpit command it will display the command name.

I will implement it in my branch and then you can have a look. If it is not good I can remove it.
