### ISSUE TITLE
adding query description to TSDoc

### ISSUE THREAD

**Issue by TobiasHH** [pushpak1300/cypress-mailpit#51]
Actual, there is no description how to use the Search query commands. To improve usability the TSDoc should describe how to use it or link to the docs for the search filters side https://mailpit.axllent.org/docs/usage/search-filters/

**Comment by pushpak1300** [comment]
I think this is really good suggestion. If you want to work on this then let me know I'll assign you this issue.
https://tsdoc.org/pages/tags/link/

**Comment by TobiasHH** [comment]
I can work on it. Question is should I add the link or change the description? Or do you have any other Idea?

**Comment by pushpak1300** [comment]
So I will simply add something like this.
```ts
/**
* Search all mails from the mailbox using query.
* @param query {@link https://mailpit.axllent.org/docs/usage/search-filters/ | Query Refrence}
* @param start
* @param limit
*/
mailpitSearchEmails(query: string, start?: number, limit?: number): Chainable<MessagesSummary>;
```
This lokks something like this. which I guess simple without changing lot of descriptions.

<img width="669" alt="Screenshot 2024-11-13 at 9 44 11 AM" src="https://github.com/user-attachments/assets/f5e7251b-d401-4bf2-8665-3af05720fee1">

**Comment by TobiasHH** [comment]
Looks good. Must be done on all bySearch commands.

**Comment by TobiasHH** [comment]
PS: alltready used the new deleteBySearch an it works fine!!!!

Thanks allot!
