### ISSUE TITLE
Docs:  Using trailing `/` in `MAILPIT_URL` silently breaks API requests

### ISSUE THREAD

**Issue by harveysanders** [pushpak1300/cypress-mailpit#53]
The docs suggest setting a `MAILPIT_URL` with a trailing slash, however the code does not account for this. This results in a double slash in the URL when used in the Cypress commands.
https://github.com/pushpak1300/cypress-mailpit/blob/91a78f7d143263e4d0722f0ed8af77660a70beb8/README.md?plain=1#L78-L88

https://github.com/pushpak1300/cypress-mailpit/blob/91a78f7d143263e4d0722f0ed8af77660a70beb8/src/MailpitCommands.ts#L43-L46

I know this is outside of the purview of this project, but at least some of the bad requests respond with `200`s, leading the user to believe that the request was successful. Here is an example of the `cy.mailpitDeleteAllEmails()` command returning a `200` status code, even though the request was malformed and no emails were deleted:

![image](https://github.com/user-attachments/assets/2af5afeb-e850-4f39-9461-815af7507aa2)

One solution would be to simply remove the trailing slash from the `MAILPIT_URL` in the README example, but we could go a step further and add a check in the code to remove the trailing slash if it exists. This would prevent the double slash issue and ensure that the URL is always formatted correctly.

```typescript
class MailpitCommands {
  private readonly baseUrl: string;

  //...

  private mailpitUrl(path: string, isApi = true): string {
    // the URL constructor will automatically remove the trailing slash if it exists
    const url = new URL(`${isApi ? "api" : ""}${path}`, this.baseUrl);
    return url.toString();
  }

  // ...
}
```

I could submit a PR if you like, but I wanted to get your thoughts first. Thanks!

**Comment by pushpak1300** [comment]
I guess simple change in readme can fix this. Handling this in code side feel like a overkill.

Feel free to raise MR for this.

**Comment by pushpak1300** [comment]
I fixed this in https://github.com/pushpak1300/cypress-mailpit/commit/c63e17134bd6f4d6ae5be437602de7a022f51cd2
